name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [hoohoo_web]

    steps:
    - uses: actions/checkout@v4

    - name: Install and build ${{ matrix.project }}
      run: |
        cd ${{ matrix.project }}
        npm ci
        npm run build:prod

    - name: Upload dist for ${{ matrix.project }}
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.project }}
        path: ${{ matrix.project }}/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [hoohoo_web]

    steps:
    - name: Download dist for ${{ matrix.project }}
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ matrix.project }}
        path: ${{ matrix.project }}/dist/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to S3
      run: |
        aws s3 sync ${{ matrix.project }}/dist/ s3://www.earthmera.com/ --delete --acl public-read
